### ISSUE TITLE
question about a "staging" homepage

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghosttheme#11]
Question, please: Is there any way to alter our theme such that the homepage can be worked on at a URL like /homepage ? That would be like a simple staging server, n'est-ce pas? Maybe it takes longer than is worth the time.

**Comment by norberthnd** [comment]
That's possible, here's how I would do it:
- duplicate the `index.hbs` template 
- create a new route in the `routes.yaml` file 
- set the duplicated template for the new route 
- upload the `routes.yaml` to activate the route

**Comment by unitof** [comment]
Just invited you as admin so you can access whatever you need in future.

Here is current version:
```
routes:

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
